### ISSUE TITLE
Crate Maintainer

### ISSUE THREAD

**Issue by HexSleeves** [alexschrod/bevy_doryen#1]
Hello! I found this crate a while badk, but I am circling back because I would like to upgrade it to bevy 0.9 and the latest doryen-rs. I have a local copy with it fully functional on the latest for each repo, but was wondering if you plan to maintain this crate, or if you would mind if I take over? This is wonderful work. I think a future enhancement would be to ditch doryen-rs rendering and have bevy handle it all

**Comment by ilyvion** [comment]
Hi!

I've been dealing with some medical stuff lately (was hospitalized Jan 31 to Feb 8 and am currently recovering from surgery) so I've been unable to see and reply to this until now.

I do plan on updating it, but if you've already got it working, I'd be happy to take a PR doing it for me, too. 😅

This project's goal for me was mainly to use Bevy's ECS with Doryen, so switching over to using Bevy's renderer wasn't really planned on my end, but if it could be done well enough that it behaves exactly the same as the Doryen renderer does, then I'd be all for it.

I think there's a separate Bevy/Doryen project that already does this, although I haven't looked all that much into it.

**Comment by HexSleeves** [comment]
Most definitely I will work on getting you a PR up. I actually added doryen-rs as a backend to `brltk` so once you upgrade this repo, ill remove the custom code I ported and use this lib directly as a backend.

https://github.com/YendorEngine/BRLTK

**Comment by ilyvion** [comment]
Sorry for taking so long. As "luck" would have it, I had a fairly severe depressive episode not long after my surgery that lasted until fairly recently, so I wasn't able to address this until now. However, with our latest [0.3.0 release](https://github.com/alexschrod/bevy_doryen/releases/tag/v0.3.0), `bevy_doryen` is once again on par with the latest release of Bevy.

Assuming no unforeseen hurdles, I intend to keep this library updated going forward. I see from your repo that there hasn't been much progress since you made your last comment, but should you want to pick up the ball again, this library is at least ready for you now. 😃
